# Keep bring-up observable. USB CDC console defaults come from the PicoSystem
# board definition.
CONFIG_ADC=y
CONFIG_DISPLAY=y
CONFIG_GPIO=y
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_PWM=y
CONFIG_REBOOT=y
CONFIG_RETAINED_MEM=y
CONFIG_RETENTION=y
CONFIG_RETENTION_BOOT_MODE=y
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_SHELL_BACKEND_SERIAL_CHECK_DTR=y
CONFIG_SHELL_BACKEND_SERIAL_LOG_MESSAGE_QUEUE_SIZE=512
CONFIG_SHELL_BACKEND_SERIAL_RX_RING_BUFFER_SIZE=128
CONFIG_SHELL_CMDS_RESIZE=n
CONFIG_SHELL_DEVICE_HELPERS=n
CONFIG_SHELL_LOG_BACKEND=y
CONFIG_SHELL_PROMPT_UART="picosystem:~$ "
CONFIG_SHELL_PROMPT_CHANGE=n
CONFIG_SHELL_STACK_SIZE=2048
CONFIG_SHELL_STATS=n
CONFIG_SHELL_WILDCARD=n
CONFIG_SPI=y
CONFIG_ST7789V_RGB565X=y
CONFIG_UART_LINE_CTRL=y
CONFIG_DATE_SHELL=n
CONFIG_DEVICE_SHELL=n
CONFIG_DEVMEM_SHELL=n
CONFIG_KERNEL_SHELL=n
CONFIG_ASSERT=y
CONFIG_MAIN_STACK_SIZE=2048
