/*
 * Copyright (c) 2026 Toy Factory contributors
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include "garden_model_file.h"

#include <ctype.h>
#include <errno.h>
#include <inttypes.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#define GARDEN_MODEL_TEMP_PATH_CAPACITY 4096U
#define GARDEN_MODEL_VALUES_PER_LINE    16U

static uint32_t read_u32_le(const uint8_t *bytes)
{
	return (uint32_t)bytes[0] | ((uint32_t)bytes[1] << 8U) | ((uint32_t)bytes[2] << 16U) |
	       ((uint32_t)bytes[3] << 24U);
}

static int io_error(void)
{
	return (errno == 0) ? -EIO : -errno;
}

static int temporary_path(const char *path, char *temporary, size_t capacity)
{
	if ((path == NULL) || (*path == '\0') || (temporary == NULL)) {
		return -EINVAL;
	}
	const int length = snprintf(temporary, capacity, "%s.tmp", path);
	if ((length < 0) || ((size_t)length >= capacity)) {
		return -ENAMETOOLONG;
	}
	return 0;
}

static int finish_atomic_file(FILE *stream, const char *temporary, const char *path,
			      int write_error)
{
	int err = write_error;
	if ((err == 0) && (fflush(stream) != 0)) {
		err = io_error();
	}
	if ((fclose(stream) != 0) && (err == 0)) {
		err = io_error();
	}
	if ((err == 0) && (rename(temporary, path) != 0)) {
		err = io_error();
	}
	if (err != 0) {
		(void)remove(temporary);
	}
	return err;
}

static bool symbol_is_valid(const char *symbol)
{
	if ((symbol == NULL) || !(isalpha((unsigned char)symbol[0]) || (symbol[0] == '_'))) {
		return false;
	}
	for (size_t index = 1U; symbol[index] != '\0'; ++index) {
		if (!(isalnum((unsigned char)symbol[index]) || (symbol[index] == '_'))) {
			return false;
		}
	}
	return true;
}

static int write_i8_vector(FILE *stream, const int8_t *values, size_t count, size_t indent)
{
	if (fputc('{', stream) == EOF) {
		return -EIO;
	}
	for (size_t index = 0U; index < count; ++index) {
		if ((index % GARDEN_MODEL_VALUES_PER_LINE) == 0U) {
			if (fprintf(stream, "\n%*s", (int)indent, "") < 0) {
				return -EIO;
			}
		}
		if (fprintf(stream, "%d%s", (int)values[index], (index + 1U < count) ? ", " : "") <
		    0) {
			return -EIO;
		}
	}
	return (fprintf(stream, "\n%*s}", (int)(indent - 1U), "") < 0) ? -EIO : 0;
}

static int write_u8_vector(FILE *stream, const uint8_t *values, size_t count)
{
	if (fputc('{', stream) == EOF) {
		return -EIO;
	}
	for (size_t index = 0U; index < count; ++index) {
		if (fprintf(stream, "%s%uU", (index == 0U) ? "" : ", ", values[index]) < 0) {
			return -EIO;
		}
	}
	return (fputc('}', stream) == EOF) ? -EIO : 0;
}

static int write_i32_vector(FILE *stream, const int32_t *values, size_t count, size_t indent)
{
	if (fputc('{', stream) == EOF) {
		return -EIO;
	}
	for (size_t index = 0U; index < count; ++index) {
		if ((index % 8U) == 0U) {
			if (fprintf(stream, "\n%*s", (int)indent, "") < 0) {
				return -EIO;
			}
		}
		if (fprintf(stream, "INT32_C(%" PRId32 ")%s", values[index],
			    (index + 1U < count) ? ", " : "") < 0) {
			return -EIO;
		}
	}
	return (fprintf(stream, "\n%*s}", (int)(indent - 1U), "") < 0) ? -EIO : 0;
}

static int write_i8_matrix(FILE *stream, const int8_t *values, size_t rows, size_t columns,
			   size_t indent)
{
	if (fputs("{\n", stream) == EOF) {
		return -EIO;
	}
	for (size_t row = 0U; row < rows; ++row) {
		if (fprintf(stream, "%*s", (int)indent, "") < 0) {
			return -EIO;
		}
		int err = write_i8_vector(stream, &values[row * columns], columns, indent + 1U);
		if (err != 0) {
			return err;
		}
		if (fprintf(stream, "%s\n", (row + 1U < rows) ? "," : "") < 0) {
			return -EIO;
		}
	}
	return (fprintf(stream, "%*s}", (int)(indent - 1U), "") < 0) ? -EIO : 0;
}

static int write_model_definition(FILE *stream, const struct picosystem_garden_neural_model *model,
				  const char *symbol, uint32_t fingerprint)
{
	if (fprintf(stream,
		    "/* Generated by toy-factory-garden-train; model CRC32 %08" PRIx32
		    ". */\n#include <stdint.h>\n\n#include \"garden_agent_neural.h\"\n\n"
		    "const struct picosystem_garden_neural_model %s = {\n"
		    "\t.magic = UINT32_C(0x%08" PRIx32 "),\n"
		    "\t.model_version = %uU,\n"
		    "\t.feature_version = %uU,\n"
		    "\t.model_size = %uU,\n"
		    "\t.hidden_shift = %uU,\n"
		    "\t.output_shift = %uU,\n"
		    "\t.candidate_hidden_shift = %uU,\n\t.reserved = ",
		    fingerprint, symbol, model->magic, model->model_version, model->feature_version,
		    model->model_size, model->hidden_shift, model->output_shift,
		    model->candidate_hidden_shift) < 0) {
		return -EIO;
	}
	int err = write_u8_vector(stream, model->reserved, sizeof(model->reserved));
	if ((err != 0) || (fputs(",\n\t.hidden_bias = ", stream) == EOF)) {
		return (err != 0) ? err : -EIO;
	}
	err = write_i32_vector(stream, model->hidden_bias,
			       PICOSYSTEM_GARDEN_NEURAL_HIDDEN_UNIT_COUNT, 2U);
	if ((err != 0) || (fputs(",\n\t.hidden_weights = ", stream) == EOF)) {
		return (err != 0) ? err : -EIO;
	}
	err = write_i8_matrix(stream, &model->hidden_weights[0][0],
			      PICOSYSTEM_GARDEN_NEURAL_HIDDEN_UNIT_COUNT,
			      PICOSYSTEM_GARDEN_NEURAL_HIDDEN_INPUT_COUNT, 2U);
	if ((err != 0) || (fputs(",\n\t.action_bias = ", stream) == EOF)) {
		return (err != 0) ? err : -EIO;
	}
	err = write_i32_vector(stream, model->action_bias, PICOSYSTEM_GARDEN_AGENT_ACTION_COUNT,
			       2U);
	if ((err != 0) || (fputs(",\n\t.action_weights = ", stream) == EOF)) {
		return (err != 0) ? err : -EIO;
	}
	err = write_i8_matrix(stream, &model->action_weights[0][0],
			      PICOSYSTEM_GARDEN_AGENT_ACTION_COUNT,
			      PICOSYSTEM_GARDEN_NEURAL_HIDDEN_UNIT_COUNT, 2U);
	if ((err != 0) ||
	    (fprintf(stream, ",\n\t.priority_bias = INT32_C(%" PRId32 "),\n\t.priority_weights = ",
		     model->priority_bias) < 0)) {
		return (err != 0) ? err : -EIO;
	}
	err = write_i8_vector(stream, model->priority_weights,
			      PICOSYSTEM_GARDEN_NEURAL_HIDDEN_UNIT_COUNT, 2U);
	if ((err != 0) || (fputs(",\n\t.memory_bias = ", stream) == EOF)) {
		return (err != 0) ? err : -EIO;
	}
	err = write_i32_vector(stream, model->memory_bias, PICOSYSTEM_GARDEN_AGENT_MEMORY_WIDTH,
			       2U);
	if ((err != 0) || (fputs(",\n\t.memory_weights = ", stream) == EOF)) {
		return (err != 0) ? err : -EIO;
	}
	err = write_i8_matrix(stream, &model->memory_weights[0][0],
			      PICOSYSTEM_GARDEN_AGENT_MEMORY_WIDTH,
			      PICOSYSTEM_GARDEN_NEURAL_HIDDEN_UNIT_COUNT, 2U);
	if ((err != 0) || (fputs(",\n\t.candidate_hidden_bias = ", stream) == EOF)) {
		return (err != 0) ? err : -EIO;
	}
	err = write_i32_vector(stream, model->candidate_hidden_bias,
			       PICOSYSTEM_GARDEN_NEURAL_CANDIDATE_UNIT_COUNT, 2U);
	if ((err != 0) || (fputs(",\n\t.candidate_hidden_weights = ", stream) == EOF)) {
		return (err != 0) ? err : -EIO;
	}
	err = write_i8_matrix(stream, &model->candidate_hidden_weights[0][0],
			      PICOSYSTEM_GARDEN_NEURAL_CANDIDATE_UNIT_COUNT,
			      PICOSYSTEM_GARDEN_NEURAL_HIDDEN_UNIT_COUNT, 2U);
	if ((err != 0) || (fputs(",\n\t.candidate_feature_weights = ", stream) == EOF)) {
		return (err != 0) ? err : -EIO;
	}
	err = write_i8_matrix(stream, &model->candidate_feature_weights[0][0],
			      PICOSYSTEM_GARDEN_NEURAL_CANDIDATE_UNIT_COUNT,
			      PICOSYSTEM_GARDEN_NEURAL_CANDIDATE_FEATURE_COUNT, 2U);
	if ((err != 0) || (fprintf(stream,
				   ",\n\t.candidate_output_bias = INT32_C(%" PRId32
				   "),\n\t.candidate_output_weights = ",
				   model->candidate_output_bias) < 0)) {
		return (err != 0) ? err : -EIO;
	}
	err = write_i8_vector(stream, model->candidate_output_weights,
			      PICOSYSTEM_GARDEN_NEURAL_CANDIDATE_UNIT_COUNT, 2U);
	if ((err != 0) || (fputs(",\n};\n", stream) == EOF)) {
		return (err != 0) ? err : -EIO;
	}
	return 0;
}

int toy_factory_garden_model_fingerprint(const struct picosystem_garden_neural_model *model,
					 uint32_t *fingerprint)
{
	if ((model == NULL) || (fingerprint == NULL)) {
		return -EINVAL;
	}
	uint8_t encoded[PICOSYSTEM_GARDEN_NEURAL_FILE_SIZE];
	const int err = picosystem_garden_neural_model_encode(model, encoded, sizeof(encoded));
	if (err != 0) {
		return err;
	}
	*fingerprint = read_u32_le(&encoded[12]);
	return 0;
}

int toy_factory_garden_model_read(const char *path, struct picosystem_garden_neural_model *model,
				  uint32_t *fingerprint)
{
	if ((path == NULL) || (*path == '\0') || (model == NULL)) {
		return -EINVAL;
	}
	FILE *const stream = fopen(path, "rb");
	if (stream == NULL) {
		return io_error();
	}
	uint8_t encoded[PICOSYSTEM_GARDEN_NEURAL_FILE_SIZE];
	const size_t count = fread(encoded, 1U, sizeof(encoded), stream);
	int err = 0;
	if (count != sizeof(encoded)) {
		err = ferror(stream) ? io_error() : -ERANGE;
	} else if (fgetc(stream) != EOF) {
		err = -ERANGE;
	} else if (ferror(stream)) {
		err = io_error();
	}
	if ((fclose(stream) != 0) && (err == 0)) {
		err = io_error();
	}
	if (err != 0) {
		return err;
	}
	err = picosystem_garden_neural_model_decode(encoded, sizeof(encoded), model);
	if ((err == 0) && (fingerprint != NULL)) {
		*fingerprint = read_u32_le(&encoded[12]);
	}
	return err;
}

int toy_factory_garden_model_write_binary(const char *path,
					  const struct picosystem_garden_neural_model *model,
					  uint32_t *fingerprint)
{
	if ((path == NULL) || (*path == '\0') || (model == NULL)) {
		return -EINVAL;
	}
	uint8_t encoded[PICOSYSTEM_GARDEN_NEURAL_FILE_SIZE];
	int err = picosystem_garden_neural_model_encode(model, encoded, sizeof(encoded));
	if (err != 0) {
		return err;
	}
	char temporary[GARDEN_MODEL_TEMP_PATH_CAPACITY];
	err = temporary_path(path, temporary, sizeof(temporary));
	if (err != 0) {
		return err;
	}
	FILE *const stream = fopen(temporary, "wb");
	if (stream == NULL) {
		return io_error();
	}
	const int write_error =
		(fwrite(encoded, 1U, sizeof(encoded), stream) == sizeof(encoded)) ? 0 : io_error();
	err = finish_atomic_file(stream, temporary, path, write_error);
	if ((err == 0) && (fingerprint != NULL)) {
		*fingerprint = read_u32_le(&encoded[12]);
	}
	return err;
}

int toy_factory_garden_model_write_c(const char *path,
				     const struct picosystem_garden_neural_model *model,
				     const char *symbol, uint32_t fingerprint)
{
	if ((path == NULL) || (*path == '\0') || (model == NULL) || !symbol_is_valid(symbol)) {
		return -EINVAL;
	}
	uint32_t actual_fingerprint;
	int err = toy_factory_garden_model_fingerprint(model, &actual_fingerprint);
	if (err != 0) {
		return err;
	}
	if (actual_fingerprint != fingerprint) {
		return -EILSEQ;
	}
	char temporary[GARDEN_MODEL_TEMP_PATH_CAPACITY];
	err = temporary_path(path, temporary, sizeof(temporary));
	if (err != 0) {
		return err;
	}
	FILE *const stream = fopen(temporary, "w");
	if (stream == NULL) {
		return io_error();
	}
	err = write_model_definition(stream, model, symbol, fingerprint);
	return finish_atomic_file(stream, temporary, path, err);
}
