#!/usr/bin/env bash

# Sourced by ordinary host builds and by the explicitly opt-in research check.
# Keep every research switch here: a reused CMake cache must not change the
# ecology of the player, profiler or default simulator. Tested against CMake.
readonly -a garden_default_cmake_options=(
	-DTOY_FACTORY_GARDEN_WIDE_DISPERSAL=OFF
	-DTOY_FACTORY_GARDEN_WATER_HEADROOM=OFF
	-DTOY_FACTORY_GARDEN_COMBINED_EXPERIMENT=OFF
	-DTOY_FACTORY_GARDEN_LARGE_POOL=OFF
	-DTOY_FACTORY_GARDEN_LEAF_MAINTENANCE=OFF
	-DTOY_FACTORY_GARDEN_BOTTOM_DRAINAGE=OFF
	-DTOY_FACTORY_GARDEN_LARGE_SEED_BANK=OFF
	-DTOY_FACTORY_GARDEN_SEED_RESERVE=OFF
	-DTOY_FACTORY_GARDEN_FOCAL_SEED_VETO=OFF
	-DTOY_FACTORY_GARDEN_DARK_GUARD=OFF
	-DTOY_FACTORY_GARDEN_PURCHASE_VETO=OFF
	-DTOY_FACTORY_GARDEN_NIGHT_CAPACITY=OFF
	-DTOY_FACTORY_GARDEN_WET_GERMINATION=OFF
	-DTOY_FACTORY_GARDEN_DAWN_FINISH=OFF
	-DTOY_FACTORY_GARDEN_SEED_ORDER=OFF
	-DTOY_FACTORY_GARDEN_SEED_SPACING=OFF
	-DTOY_FACTORY_GARDEN_CANOPY_TRANSMISSION=OFF
	-DTOY_FACTORY_GARDEN_PLANT_SLOTS=OFF
	-DTOY_FACTORY_GARDEN_FULL_POOL=OFF
)
